### ISSUE TITLE
bug when upload map from url, and click to calculate sample size

### ISSUE THREAD

**Issue by vsoch** [neuropower/neuropower-web#21]
Environment:

Request Method: GET
Request URL: http://127.0.0.1/neuropowersamplesize/

Django Version: 1.9.2
Python Version: 2.7.11
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'neuropowertoolbox',
 'crispy_forms',
 'djangosecure',
 'sslserver',
 'djcelery',
 'kombu.transport.django']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'djangosecure.middleware.SecurityMiddleware']

Traceback:

File "/opt/conda/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/opt/conda/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "./neuropowertoolbox/views.py" in neuropowersamplesize
  294.             powerpred =  {k:1-neuropowermodels.altCDF(v,projected_effect,float(mixdata.sigma),exc=float(parsdata.ExcZ),method="RFT") for k,v in thresholds.items()}

File "./neuropowertoolbox/views.py" in <dictcomp>
  294.             powerpred =  {k:1-neuropowermodels.altCDF(v,projected_effect,float(mixdata.sigma),exc=float(parsdata.ExcZ),method="RFT") for k,v in thresholds.items()}

File "./neuropower/utils/neuropowermodels.py" in altCDF
  60. 		ksi = (peaks-mu)/sigma

Exception Type: TypeError at /neuropowersamplesize/
Exception Value: ufunc 'subtract' did not contain a loop with signature matching types dtype('S32') dtype('S32') dtype('S32')

**Comment by jokedurnez** [comment]
do you remember which url?
It's a function used in all calculations, so it must be something data-specific.

**Comment by vsoch** [comment]
I think it might have been [this one](http://neurovault.org/images/8718/) (the download link) but I'm not 100% sure.
