### ISSUE TITLE
comparison involving NaN

### ISSUE THREAD

**Issue by jhbalsters** [neuropower/neuropower-web#35]
Hi

I'm getting the following error message when I upload my data. The .nii files are SPM thresholded images. I tried using a few different masks to remove NaN voxels but I still get the same message. The full error output is below.

Best
Josh

Environment:

Request Method: GET
Request URL: http://neuropowertools.org/neuropowertable/

Django Version: 1.9.2
Python Version: 2.7.11
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'neuropowertoolbox',
 'crispy_forms',
 'djangosecure',
 'sslserver',
 'djcelery',
 'opbeat.contrib.django',
 'kombu.transport.django']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'djangosecure.middleware.SecurityMiddleware',
 'opbeat.contrib.django.middleware.OpbeatAPMMiddleware']

Traceback:

File "/opt/conda/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/opt/conda/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "./neuropowertoolbox/views.py" in neuropowertable
  231.         cluster.cluster(SPM,parsdata.ExcZ,parsdata.peaktable)

File "./neuropower/utils/cluster.py" in cluster
  36. 					if spm_ext[m,n,o]>exc:

File "/opt/conda/lib/python2.7/decimal.py" in __lt__
  883.         ans = self._compare_check_nans(other, context)

File "/opt/conda/lib/python2.7/decimal.py" in _compare_check_nans
  789.                                             other)

File "/opt/conda/lib/python2.7/decimal.py" in _raise_error
  3873.         raise error(explanation)

Exception Type: InvalidOperation at /neuropowertable/
Exception Value: comparison involving NaN

**Comment by jokedurnez** [comment]
Bug fixed in commit f54b1f6908d25c396ad3d024f85847d21958f874.
